### ISSUE TITLE
Bug - Instagram display message

### ISSUE THREAD

**Issue by CindyTsai1** [CS2103AUG2017-W14-B3/main#103]
When adding a person with Instagram and without twitter, the instagram field in the success message is blank.

When adding a person with Twitter and without instagram, the instagram field in the success message shows the twitter account.

**Comment by CindyTsai1** [comment]
Even editing instagram does not display the correct success message.
In general, the instagram display is displaying the twitter

**Comment by danielbrzn** [comment]
Fixed in #121
