### ISSUE TITLE
Suggestion - Readable tag colours

### ISSUE THREAD

**Issue by thehelpfulbees** [CS2103AUG2017-W14-B3/main#111]
It is not possible to read the tag highlighted in yellow on my screen. I really like the multicoloured tags but maybe constraining them a bit could help. 

<img width="237" alt="screen shot 2017-11-03 at 3 12 58 pm" src="https://user-images.githubusercontent.com/4385818/32363318-b57c8f40-c0a9-11e7-8aed-4f3b7dc644df.png">

**Comment by JunQuann** [comment]
#144
