### ISSUE TITLE
Suggestion - sort

### ISSUE THREAD

**Issue by DarrenCzen** [CS2103AUG2017-W14-B3/main#114]
![image](https://user-images.githubusercontent.com/29244334/32363522-bf2c80e4-c0aa-11e7-971e-cad411029770.png)

the sort is case sensitive.  The sort can be non-case sensitive

**Comment by DarrenCzen** [comment]
Thanks for your recommendation. I just implemented something similar today because of your recommendation!

**Comment by DarrenCzen** [comment]
Alternatively, you can do this. which is to convert name from dAn to Dan

https://github.com/nus-cs2103-AY1718S1/addressbook-level4/pull/79/commits/cf57e5e78374ec3ee69125e8342ed27c9efa06da

**Comment by tbhbhbh** [comment]
Case-insensitive sort implemented in PR #125 

Thanks Darren for your suggestion!
