### ISSUE TITLE
Major bug - crash on editing to add a DP, destroyed my addressbook

### ISSUE THREAD

**Issue by thehelpfulbees** [CS2103AUG2017-W14-B3/main#116]
The app froze on this screen when I ran the command
'edit 8 dp/vhjdljfd' (not exact keysmash)
And when I force quit and reopened, the app opens, displays the UI but no data, and cannot be interacted with. I've tried reopening multiple times, the app can no longer be used.

<img width="921" alt="screen shot 2017-11-03 at 3 23 19 pm" src="https://user-images.githubusercontent.com/4385818/32363594-181ed5f8-c0ab-11e7-82a9-e34594cf3d0e.png">

**Comment by JunQuann** [comment]
#122
