### ISSUE TITLE
Bug - Can overwrite commands with other commands using `alias` command

### ISSUE THREAD

**Issue by thehelpfulbees** [CS2103AUG2017-W14-B3/main#117]
It's possible to overwrite commands with other the `alias` command, e.g. running:
`alias add find`
will mean that the `add` keyword is now handles as a `find` command. Users can work around this by adding an alias for the 'lost' command, e.g. `alias a add` will allow me to add users using `a`, or by rewriting the alias with `alias add add` but I definitely didn't think to do that at first, and it would be better if you just didn't let me overwrite command words.

**Comment by danielbrzn** [comment]
Fixed in #123.

Thanks for pointing it out 👍
